#!/usr/bin/env bash

URL_PREFIX="https://raw.githubusercontent.com/isaacanthony/infosec-linter/master"

echo "Checking for sensitive files..."

git ls-files > .git-files
git ls-files --exclude-standard --others >> .git-files
curl -s $URL_PREFIX/data/files.txt | \
  grep "^[a-z]" | \
  xargs -I {} grep -i --color=auto {} .git-files
rm .git-files
echo

echo "Checking for sensitive values..."

curl -s $URL_PREFIX/data/keywords.txt | \
  grep "^[a-z]" | \
  xargs -I {} git grep -in --color=auto {} .
echo

echo "Complete."
