#!/usr/bin/env bash

echo "Checking for sensitive files..."

cat data/suffixes.txt | \
  grep "^[a-z]" | \
  xargs -I {} find . -name "*.{}"
echo

echo "Checking for sensitive values..."

cat data/keywords.txt | \
  grep "^[a-z]" | \
  xargs -I {} grep -irn {} . --color=auto
echo

echo "Complete."
